### PR TITLE
no

### PR DESCRIPTION
**Pull request by akhilnarang**
just no

### CODE REVIEW

**Comment by Techno-Disaster** [comment]
Why bully, also too lazy send proper PR please :)

**Comment by SphericalKat** [comment]
Add to path dumbass

**Comment by Techno-Disaster** [comment]
> Add to path dumbass

what level of stalking is this, how did you even get here kek. Also ik but too lazy kek

**Review by Techno-Disaster — COMMENTED** [review]
Ah yes thanks, I really need to do some cleanup, most of the stuff is just copy pasted shit from websites telling me how to install frameworks

**Comment by smartass08** [comment]
DebOps

**Pull request merged**
